config/routes.rb
InstagramClone::Application.routes.draw do

  get "comments/new"
  get "comments/create"
  root 'posts#index'

  devise_for :users

  resources :users do
    resources :orders
  end

  resources :posts do
    resources :comments
    resources :charges
  end

  resources :tags do
    resources :posts
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :post

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base

  after_create :send_new_post_email

  validates :price, numericality: { greater_than: 0, less_than: 999999 }

  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :comments

  has_attached_file :image,
                    styles: { medium: "300x300>" }, # does not change aspect ratio
                    storage: :s3,
                    s3_credentials: {
                      # following need to be set locally and in Heroku with heroku config:set...
                      access_key_id: ENV['S3_ACCESS_KEY'],
                      secret_access_key: ENV['S3_SECRET_KEY']
                    },
                    bucket: 'instagram_clone_aws'

  def self.for_tag_or_all(tag_name)
    if tag_name
      # find all posts linked to the given tag
      @posts = Tag.find_by(name: tag_name).posts
    else
      @posts = Post.all
    end
  end

  def tag_names
    tags.map { |tag| tag.name }.join(' ')
  end

  def tag_names=(tag_names)
    self.tags = tag_names.split(/,\s?/).map do |tag_name|
      Tag.find_or_create_by(name: tag_name)
    end
  end

  def send_new_post_email
    PostMailer.new_post(self, self.user).deliver!
  end


end # of class

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_and_belongs_to_many :posts

  def to_param # overidden
    name # for 'happy urls which use tag /name/, not default; /id/'
  end

  def to_s
    "##{name}"
  end

end # of class

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :orders
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end # of class

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  before_action :get_related_post, only: [:create, :new]

  def new
  end

  def create
    @amount = (@post.price * 100).to_i # Stripe needs pounds converted to pence
    customer = Stripe::Customer.create(
      email: current_user.email, # assumes purchases from authenticated user
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: "Purchase of #{@post.title}",
      currency: 'GBP'
    )
    Order.create(user: current_user, product_id: @post.id, product_cost: @post.price)


  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end

  #helper
  def get_related_post
    @post = Post.find(params[:post_id])
  end

end # of class

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :fetch_post, only: [:new, :create]

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(params[:comment].permit(:text))
    current_user.comments << @comment
    @post.comments << @comment
    if @comment.save
      redirect_to posts_path
    else
      # flash[:error] = 'There was a problem'
      render 'new'
    end

  end # of class

  # helper
  def fetch_post
    @post = Post.find(params[:post_id])
  end

end # of class

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
  before_action :fetch_post, only: [:edit, :show, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post].permit(:title, :price, :image, :tag_names))
    current_user.posts << @post
    # adds this post to the current user's list of posts
    # current_user.posts << @post
    if @post.save
      redirect_to posts_path
    else
      # flash[:error] = 'There was a problem'
      render 'new'
    end
  end

  def index
    # display all or just those tagged, if tag provided
    @posts = Post.for_tag_or_all params[:tag_id]
  end

  def show
  end

  def update
    @post = Post.find(params[:id])
    @post.update(params[:post].permit(:title, :price))
    if @post.save
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to '/posts'
  end

  # helper
  def fetch_post
    @post = Post.find(params[:id])
  end

end # of class

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/charges/create.html.erb
<h2>Thanks, your order has been received. Your card will be charged <strong><%= number_to_currency(@post.price) %></strong>.</h2>

app/views/charges/new.html.erb
<%= form_tag post_charges_path(@post) do %>
  <article>
    <label class="amount">
      <span>Amount: <%= number_to_currency(@post.price) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-email=<%= current_user.email.to_json %>
          data-key=<%= Rails.configuration.stripe[:publishable_key].to_json %>
          data-description="A month's subscription"
          data-currency="GBP"
          data-amount=<%= (@post.price * 100).to_json %>></script>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :text %>
  <%= f.text_area :text %>

  <%= f.submit %>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name == :notice ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul class="hmenu right">
      <%= render 'devise/menu/registration_items' %>
      <%= render 'devise/menu/login_items' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Instagram Clone" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Instagram Clone" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post, html: {multipart: true} do |f| %>
  <p>
    <%= f.label :title, 'Title' %>
    <%= f.text_field :title %>

    <%= f.label :price, 'Price' %>
    <%= f.text_field :price %>

    <%= f.label :tag_names, 'Tags' %>
    <%= f.text_field :tag_names, id: "tag-input" %>

    <%= f.label :image, 'Image' %>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/_post.html.erb
<h1><%= post.title %></h1>
<%= image_tag post.image.url(:medium), class: 'instagram-upload' %>
<br>
<% post.tags.each do |tag| %>
  <%= link_to tag, tag_posts_path(tag) %>
<% end %>
<br>
<br>
<%= button_to 'Add comment', new_post_comment_path(post), method: :get %>
<%= link_to 'Edit', edit_post_path(post) %>
<%= link_to 'Delete', post_path(post), method: :delete %>
<%= number_to_currency(post.price) %>
<%= button_to 'Buy now!', new_post_charge_path(post), method: :get %>
<br>
<% post.comments.each do |comment| %>
  <p><%= comment.text %></p>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render @posts %>

app/views/posts/new.html.erb
<%= render 'form' %>